import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex justify-center items-center ">
          <Link
            href="/"
            className="w-full bg-teal-400 text-[5rem] flex items-center justify-center"
          >
            HOME
          </Link>
          <Link
            href="/articals"
            className="w-full bg-teal-400 text-[5rem] flex items-center justify-center"
          >
            Articles
          </Link>
          <Link
            href="/posts"
            className="w-full bg-teal-400 text-[5rem] flex items-center justify-center"
          >
            POSTS
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
